module.exports = {
  STOCK_UPDATE_INTERVAL: '*/5 * * * *', // Every 5 minutes
  INITIAL_FUNDS: {
    equity: 0,
    commodity: 0,
    currency: 100000
  },
  STOCK_SYMBOLS: [
    "AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "NVDA", "META", "NFLX", "DIS", "BABA",
    "V", "MA", "JPM", "JNJ", "WMT", "PG", "HD", "BAC", "ABBV", "PFE",
    "KO", "PEP", "COST", "AVGO", "CRM", "TMO", "ACN", "CVX", "NKE", "MRK",
    "ABT", "ADBE", "TXN", "LLY", "NEE", "DHR", "QCOM", "BMY", "PM", "T",
    "UNP", "LOW", "HON", "UPS", "RTX", "BLK", "AMAT", "SYK", "LMT", "MDT"
  ],
  COMPANY_NAMES: {
    AAPL: "Apple Inc.",
    MSFT: "Microsoft Corporation", 
    GOOGL: "Alphabet Inc.",
    AMZN: "Amazon.com Inc.",
    TSLA: "Tesla Inc.",
    NVDA: "NVIDIA Corporation",
    META: "Meta Platforms Inc.",
    NFLX: "Netflix Inc.",
    DIS: "Walt Disney Company",
    BABA: "Alibaba Group",
    V: "Visa Inc.",
    MA: "Mastercard Inc.",
    JPM: "JPMorgan Chase",
    JNJ: "Johnson & Johnson",
    WMT: "Walmart Inc.",
    PG: "Procter & Gamble",
    HD: "Home Depot Inc.",
    BAC: "Bank of America",
    ABBV: "AbbVie Inc.",
    PFE: "Pfizer Inc.",
    KO: "Coca-Cola Company",
    PEP: "PepsiCo Inc.",
    COST: "Costco Wholesale",
    AVGO: "Broadcom Inc.",
    CRM: "Salesforce Inc.",
    TMO: "Thermo Fisher Scientific",
    ACN: "Accenture PLC",
    CVX: "Chevron Corporation",
    NKE: "Nike Inc.",
    MRK: "Merck & Co.",
    ABT: "Abbott Laboratories",
    ADBE: "Adobe Inc.",
    TXN: "Texas Instruments",
    LLY: "Eli Lilly",
    NEE: "NextEra Energy",
    DHR: "Danaher Corporation",
    QCOM: "QUALCOMM Inc.",
    BMY: "Bristol Myers Squibb",
    PM: "Philip Morris",
    T: "AT&T Inc.",
    UNP: "Union Pacific",
    LOW: "Lowes Companies",
    HON: "Honeywell",
    UPS: "United Parcel Service",
    RTX: "Raytheon Technologies",
    BLK: "BlackRock Inc.",
    AMAT: "Applied Materials",
    SYK: "Stryker Corporation",
    LMT: "Lockheed Martin",
    MDT: "Medtronic PLC"
  }
};